services:
  postgres:
    image: postgres:latest
    container_name: postgresRss25SB
    volumes:
      - "./.postgresql-data/db:/var/lib/postgresql"
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rss25SB
    restart: unless-stopped