services:
  postgres:
    image: postgres:latest
    container_name: postgresRss25SB
    volumes:
      - "./.databasedata/db:/var/lib/postgresql"
    environment:
      - POSTGRES_PASSWORD=rss25SB
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rss25db
    ports:
      - "5430:5432"
